site_name: "CMU 05-499/899: Celebrating Accessibility"

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/05499_numberbox.png
  favicon: assets/favicon.ico
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: brown
      accent: brown
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - announce.dismiss

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      title: On This Page
      toc_depth: 3
      permalink: true

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - markdownextradata

nav:
  - Home: index.md
  - Course Overview: overview.md
  - Syllabus: syllabus.md
  - Homework: 
      - 'Homework 1 Accessible Documents': 
          - 'homework/HW1/index.md' 
          - Parts: 
              - 'homework/HW1/1_pdf.md'
              - 'homework/HW1/2_presentation.md'
      - 'Homework 2 Disability Deep Dive':
          - 'homework/HW2/index.md'
      - 'Homework 3 Accessibility Evaluation':
          - 'homework/HW3/index.md'
  - Projects:
      - 'Project Overview':
          - projects/P0/index.md # Dummy home page; remove once we start adding projects below
      - 'Project Pitches':
          - projects/P1/index.md
      - 'Team Contract':
          - projects/P2/index.md
      - 'Project Specification':
          - projects/P3/index.md
      #- "Project 1: Hello, NodeBB!":
      #    - projects/P1/index.md
      #    - 1A Build Checkpoint: projects/P1/1_checkpoint.md
      #    - 1B Starter Task: projects/P1/2_translation.md
      #    - NodeBB Installation:
      #        - Mac: projects/P1/installation/mac.md
      #        - Windows: projects/P1/installation/windows.md
      #        - Linux (Ubuntu): projects/P1/installation/ubuntu.md
      #    - Resources and Documentation: projects/P1/documentation.md
      #    - FAQ: projects/P1/faq.md
      #- "Project 2: Collaborative Development":
      #    - projects/P2/index.md
      #    - 2A Team Process & Planning: projects/P2/1_teamprocess.md
      #    - 2B First Sprint: projects/P2/2_firstsprint.md
      #    - 2C Second Sprint: projects/P2/3_secondsprint.md
      #- "Project 3: Continuous Integration + Deployment":
      #    - projects/P3/index.md
      #    - "GCP Deployment Instructions": projects/P3/deployment.md
      #- "Project 4: Architecting an LLM Integration":
      #    - projects/P4/index.md
      #- "Project 5: Open Source Excursion":
      #    - projects/P5/index.md
      #    - "5A Project and Task Selection": projects/P5/1_projectcheck.md
      #    - "5B Project Presentations, Final Report, and Reflections": projects/P5/2_projectfinal.md

  #- Hall of Fame: hall-of-fame.md
  - Canvas: https://canvas.cmu.edu/courses/42586
  - Gradescope: https://www.gradescope.com/courses/823456
  - Slack: https://join.slack.com/t/cmu-05-499-f24/shared_invite/zt-2omf3b8km-~Kwm1fmZzZaoEjJiQYYVkA
